name: Table Scraper (21f2001400@ds.study.iitm.ac.in)

on: [push]

jobs:
  scrape:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: 21f2001400@ds.study.iitm.ac.in - Install Playwright
        run: |
          npm init -y
          npm install playwright@latest
          npx playwright install --with-deps
      
      - name: 21f2001400@ds.study.iitm.ac.in - Run Scraper
        run: node scrape.js
